chore: Revert Minor dependency updates (#279) (#280)
This reverts the upgrade of the sttp client in commit
073947c7014f8c5f0e00992d7e9635292fa4c0ee.

The ugrade prevented the application to startup. It failed with an
error:

```
java.lang.Error: Defect in zio.ZEnvironment: HashSet(SttpBackend[=λ %0 → ZIO[-Any,+Throwable,+0],+{package::WebSockets & ZioStreams}]) statically known to be contained within the environment are missing
```

I have created a bug report
https://github.com/softwaremill/sttp/issues/2317